# Generated by Django 4.2.6 on 2023-11-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='foto1',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(default='http://127.0.0.1:8082/'),
        ),
        migrations.AddField(
            model_name='project',
            name='link_github',
            field=models.URLField(default='https://github.com/akbaraulia'),
        ),
        migrations.AddField(
            model_name='project',
            name='stack',
            field=models.CharField(default='default_value', max_length=100),
        ),
    ]
